Apm 92 - Travis fix (#93)
* updating the Travis configuration for supported JAVA versions

* removing JAVA 9 because of: NoClassDefFoundError: com/sun/tools/javac/file/BaseFileObject